# Configuration vars for cmd/app
[app]
name = "Fiber starter"
port = ":8800"
idle-timeout = 5 # As seconds
print-routes = false
prefork = true
production = false

[db.postgres]
dsn = "postgresql://hanif:P@ssw0rd.1@192.168.0.107:5432/go_starter" # <driver>://<username>:<password>@<host>:<port>/<database>
migrate = true
seed = true

[logger]
log-dir = "debug.log"
time-format = "" # https://pkg.go.dev/time#pkg-constants, https://github.com/rs/zerolog/blob/master/api.go#L10 
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true

[middleware.monitor]
enable = false
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = false
max = 20
expiration_seconds = 60